server:
  port: 8080
spring:
  config:
    import: classpath:mybatisplus.yml
  datasource:
    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:testdb
    url: jdbc:h2:file:./data/testdb
    username: sa
    password:
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
  #      data-locations: classpath:data.sql
  h2:
    console:
      enabled: true
      path: /h2-console
